### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by mjp0** [jimpick/utp-native-prebuilds-nodejs-mobile#1]
Firstly, thank you so much for creating this!

I'm having some trouble understanding how to use this. I cloned the repo, ran `npm i` and then `npm run build` but I can't get anything to build. I get the following log:

```
> utp-native-prebuilds-nodejs-mobile@1.7.1-8 build /Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile
> npm run clean && npm run build-ios && npm run build-android


> utp-native-prebuilds-nodejs-mobile@1.7.1-8 clean /Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile
> rm -rf utp-native prebuilds


> utp-native-prebuilds-nodejs-mobile@1.7.1-8 build-ios /Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile
> ./build-ios-arm64.sh && ./build-ios-x64.sh

Cloning into 'utp-native'...
remote: Enumerating objects: 552, done.
remote: Total 552 (delta 0), reused 0 (delta 0), pack-reused 552
Receiving objects: 100% (552/552), 194.85 KiB | 978.00 KiB/s, done.
Resolving deltas: 100% (292/292), done.
/Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile/utp-native /Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile

> utp-native@2.0.1 install /Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile/utp-native
> node-gyp-build

npm notice created a lockfile as package-lock.json. You should commit this file.
added 248 packages from 181 contributors in 4.829s
[+] no known vulnerabilities found [485 packages audited]

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: *** No rule to make target `Release/obj.target/libutp/deps/libutp/utp_internal.o', needed by `Release/utp.a'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile/node_modules/nodejs-mobile-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.7.0/bin/node" "/Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile/node_modules/nodejs-mobile-gyp/bin/node-gyp.js" "rebuild" "--target=8.0.0" "--target_arch=arm64" "--release"
gyp ERR! cwd /Volumes/dev_tests/utp-native-prebuilds-nodejs-mobile/utp-native
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v0.1.1
gyp ERR! not ok
node-gyp exited with 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utp-native-prebuilds-nodejs-mobile@1.7.1-8 build-ios: `./build-ios-arm64.sh && ./build-ios-x64.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utp-native-prebuilds-nodejs-mobile@1.7.1-8 build-ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/0fork/.npm/_logs/2018-10-05T15_27_18_429Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utp-native-prebuilds-nodejs-mobile@1.7.1-8 build: `npm run clean && npm run build-ios && npm run build-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utp-native-prebuilds-nodejs-mobile@1.7.1-8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/0fork/.npm/_logs/2018-10-05T15_27_18_566Z-debug.log
```

I'm running MacOS 10.2.6 with XCode 9.2, Node 10.10 in case that matters.

Any ideas?

*edit: just noticed that the log is with node 8.7.0 that I also tried but the end result is the same*

**Comment by paramtatv** [comment]
any luck on how is this supposed to be used

**Comment by jimpick** [comment]
It's very likely that the dependencies have changed dramatically... I don't really have time to look at it right now, as I'm not actively using it in a project.
